language: python
python:
 - "2.7"


notifications:
  irc:
    channels:
      - "chat.freenode.net#BuildAPC-docs"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
    skip_join: true